### ISSUE TITLE
Gui or Canvas elements?

### ISSUE THREAD

**Issue by Tobiidave** [justonia/UnityUrpPixelPerfectVisibility#2]
Hi, just found this excellent work so exciting.

Can we make it work on GUI elements? The current code seems to use renderers and materials - can we make GUI elements like text or buttons also render into the same Render texture?

**Comment by justonia** [comment]
@Tobiidave Unity UI is pretty much a black box. I'm not sure there is a way to 1) render just the canvas manually into an RT and 2) create a replacement shader that would be compatible with it.

What is your use case? The UI is already pixel perfect when it comes to picking. Are you thinking of world-space UI?

**Comment by Tobiidave** [comment]
Sorry. We gave up on this in September :(
